apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x81gy5url-java-springboot-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/x81gy5url-java-springboot